### ISSUE TITLE
Saga mapping to a field throws unhelpful NullReferenceException

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#3480]
Students in a training class (using 5.2.14) made public fields in their saga data class instead of properties. It looks like when the mapper runs, the expression points to the field but then (I'm guessing) we try to convert that expression into a PropertyInfo, and the PropertyInfo is null.

We could throw a much better exception.

This is something we should consider improving along with the other saga usability changes in V6?

@Particular/nservicebus-maintainers

**Comment by andreasohlund** [comment]
I have a faint memory that I've already fixed this in v6, can you verify?

**Comment by DavidBoike** [comment]
Yep, intended to verify, needed to capture. Self-assigning.

**Comment by johnsimons** [comment]
Not really a bug @andreasohlund, IMO this is just an improvement

**Comment by andreasohlund** [comment]
We have no label for that and IMO this is closer to a bug than a feature. 

Not throwing helpful exceptions => Usability bug?

**Comment by DavidBoike** [comment]
Verified that this still throws an unhelpful NullReferenceException on 6.0.0-unstable1568 (currently latest on MyGet)
