### ISSUE TITLE
Cannot move message to "Audit" table 

### ISSUE THREAD

**Issue by nguyenhuuloc304** [Particular/NServiceBus#5638]
Hi All, 

I have built a Logging Center based on NserviceBus. 

These days my SQL server have an issue with a lot of records on Logging table (over 30k records). It caused high CPU consumption of SQL server. When I check logs of application, I saw this error

```
NServiceBus.RecoverabilityExecutor: Immediate Retry is going to retry message '[Id of message]' because of an exception:
System.Exception: Failed to send message to [xxxxxxxx].[dbo].**[audit]** ---> System.Data.SqlClient.SqlException: Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: Unknown error 258.
```

It seems when **Handler** has accomplished, but Nservicebus cannot move the message into Audit table, therefore the message was still stay on Logging table (in my case).

Does anyone encounter this kind of error? Could you help to advise anything to fix this one? Thank you so much!

I also saw some more error as below:

```
NServiceBus.Transport.SQLServer.MessagePump: Sql receive operation failed System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

NServiceBus.Transport.SQLServer.RepeatedFailuresOverTimeCircuitBreaker: The circuit breaker for ReceiveText is now in the armed state

NServiceBus.Transport.SQLServer.RepeatedFailuresOverTimeCircuitBreaker: The circuit breaker for ReceiveText is now disarmed

NServiceBus.Transport.SQLServer.QueuePeeker: Sql peek operation failed System.NullReferenceException: Object reference not set to an instance of an object.
```

**Comment by SzymonPobiega** [comment]
Hi

Which version of NServiceBus and SQL Server transport do you use? The timeout errors usually mean that SQL Server database is overloaded.

**Comment by nguyenhuuloc304** [comment]
We are using NSB 7.1.4,  NSB.SQLServer 4.1.0 and SQL Server 2016. 
Issue 1: it's weird that, if there are over 30000 records in queue table, it caused high CPU consumption in SQL server, and in application, it thrown above exceptions. If I manually delete records from SQL server about 20000 records. it means there are around 10000 left, Then NSB did not thrown exceptions anymore and can work normally (I means message in queue were picked up and executed. Then the message was removed out of queue table)

Issue 2: Another thing is why there were over 30k records existed in queue table in that time. Why did not Handler pick up the message caused over 30k messages existed in the table in the same time. I'm trying to investigate this issue on our applications.

@SzymonPobiega could you help to advise for Issue 1? because it is on PROD env, we are still deleting messages manually in SQL to help NSB can work normally with less than 10k messages.

**Comment by SzymonPobiega** [comment]
Hi

Please upgrade to the latest version of the SQL Server transport (preferred) or at least to [4.1.2](https://github.com/Particular/NServiceBus.SqlServer/releases/tag/4.1.2). The problem with large queue size has been fixed in 4.1.2.

**Comment by nguyenhuuloc304** [comment]
Hi @SzymonPobiega 

Thank you so much for your advise, I will upgrade and test with my scenario. I'll update you the result.

**Comment by boblangley** [comment]
@nguyenhuuloc304 did the upgrade help with your scenario?

**Comment by nguyenhuuloc304** [comment]
Hi @boblangley , my client does not plan to upgrade it. the problem is still there.

**Comment by WilliamBZA** [comment]
Hi @nguyenhuuloc304, 

I'm going to close this issue since the fix is to update to version 4.1.2 or later.  Version 4.1.0 of NServiceBus.SqlServer is no longer supported. Upgrading to 4.1.2 should be a low-risk upgrade anyway as it is only a patch update not even a minor.

Feel free to re-open this issue if you still experience the problem after you have upgrade to a support version of the package.
